### ISSUE TITLE
Tutorial/Helps for Email Forwarder or something?

### ISSUE THREAD

**Issue by Marow** [harshitpeer/TMail-Lite#1]
What is the best to use forwarder?

Own System on Ubuntu, but what to use?
Or any free systems or something?

**Comment by harshitpeer** [comment]
Hi Marow,

I am not able to understand what exactly you are asking for.
Can you clarify your questions a bit more in detail?

**Comment by harshitpeer** [comment]
Closing this issue as no response is received since last 11 Days.
