### ISSUE TITLE
how is this supposed to work

### ISSUE THREAD

**Issue by notaila** [harshitpeer/TMail-Lite#2]
everytime i refresh i get a new mail box and it doesnt seem to auto refresh
seeing this in the test mail server link you have

**Comment by harshitpeer** [comment]
@effex1337 You will need to enable cookies on your browser (in case if that's disabled)

Check out the video in this ZIP file which shows how it's working
[7e5f98a9-ffb5-402f-869c-48efa52289bf.zip](https://github.com/harshitpeer/TMail-Lite/files/4648345/7e5f98a9-ffb5-402f-869c-48efa52289bf.zip)

**Comment by dausruddin** [comment]
It is weird that I am having the same issue. I never had problem with cookies with my browser.

I even checked it here
![Screenshot_20200626-181829](https://user-images.githubusercontent.com/5763466/85847128-84155c00-b7d9-11ea-964d-50350af831b2.jpg)

Something is wrong with the code I guess.
