### ISSUE TITLE
Code is producing an error

### ISSUE THREAD

**Issue by rsoorajs** [harshitpeer/TMail-Lite#3]
![IMG_20200630_153507_608](https://user-images.githubusercontent.com/20116017/86114384-11adc000-bae8-11ea-9e5d-79611a902ae0.jpg)

**Comment by harshitpeer** [comment]
Hi,

Please explain your issue in detail.

**Comment by rsoorajs** [comment]
yeah..it fixed now.i hosted that on heroku.but still i am not getting any email.can i use gmail imap configs for this ?

**Comment by rsoorajs** [comment]
does i need a dedicated running email server ?

**Comment by rsoorajs** [comment]
![Screenshot_2020-06-30-15-53-24-18](https://user-images.githubusercontent.com/20116017/86116828-afef5500-baeb-11ea-911d-703307f0b180.png)

**Comment by rsoorajs** [comment]
still i am not getting emails

**Comment by harshitpeer** [comment]
Your issue is not related to code but to the email settings that you have made. Check if your forwarding and everything is working fine. If your email inbox is not able to receive emails then TMail Lite will not receive the email.
