### ISSUE TITLE
How to host 

### ISSUE THREAD

**Issue by killerlearner** [harshitpeer/TMail-Lite#5]
Can you please tell how can I host it in heroku or where can I host it. Cuz I unable to understand how to host. 
 Thanks for help. 
You can contact me also in telegram for better understanding @killerlearner ( TG username)

**Comment by harshitpeer** [comment]
You can use any Hosting provider which supports PHP. I'm not sure how Heroku works, so you can do some research on how to install PHP script on Heroku.
